### ISSUE TITLE
Missing cross to close contextual catalog with main branch 0.6.x

### ISSUE THREAD

**Issue by apupier** [KaotoIO/vscode-kaoto#130]
based on 6e9408e51dade095d9fabf2d6a848714dd6c58f7 Kaoto Ui commit, the cross to close contextual catalog is missing:

![image](https://user-images.githubusercontent.com/1105127/220140765-a6772cda-891b-421d-b467-20fcacf0bd47.png)

the cross is available on OperateFirst

**Comment by kahboom** [comment]
We removed it to make the mini catalog cleaner/neater, since you can close it by clicking anywhere outside of it. Did you much prefer it with the cross? I'm not sure why it shows on operate first, I have to check if there is some inconsistency as the mini catalog rendering is different depending on where it is shown.

**Comment by apupier** [comment]
in VS Code, it is not closing when clicking elsewhere.

**Comment by apupier** [comment]
> Did you much prefer it with the cross?

No opinion. I only noticed the difference and thought I cannot close the catalog due the delay mentioned in previous comment

> I'm not sure why it shows on operate first, I have to check if there is some inconsistency as the mini catalog rendering is different depending on where it is shown.

ok, so keeping this issue opened for investigation of both the inconsistency with OperateFirst and the 10-15 seconds delay. Maybe will create separate issue later

**Comment by apupier** [comment]
reported https://github.com/KaotoIO/kaoto-ui/issues/1326 for the cross left in some cases.

Will close this issue as the slowness is covered by #132
