### ISSUE TITLE
Upgrade to Yarn v3

### ISSUE THREAD

**Issue by apupier** [KaotoIO/vscode-kaoto#270]
it seems that we must upgrade VS Code Kaoto too due to bugs in yarn v1 and react mismatch with Kogito.

follow-up on https://github.com/KaotoIO/kaoto-ui/issues/1588

Also the steps to use locally latest version will need to be updated due to `yarn link` without arguments does not exist anymore:
https://yarnpkg.com/cli/link
https://github.com/KaotoIO/vscode-kaoto/blob/main/CONTRIBUTING.md#how-to-manually-test-latest-kaoto-ui

**Comment by lordrip** [comment]
It seems that `vscode/vsce` doesn't support yarn v3 yet

 https://github.com/microsoft/vscode-vsce/issues/517

**Comment by lordrip** [comment]
We now have some situations to consider:

* Scenario # 1: `kaoto-ui@1.0.0` + `kaoto-backend@1.0.0` + `@kie-tools/*@0.27.0`
Everything works fine, no problems whatsoever

* Scenario # 2: `kaoto-ui@main-branch` + `kaoto-backend@1.0.0` + `@kie-tools/*@0.27.0`
    * `vscode-kaoto` cannot link `kaoto-ui` because `yarn v3` checks whether the dependencies are correct or not, upon linking projects (_this didn't happen in the past, so weird stuff occurred from time to time_)
    * Apart from the linking issue, the latest UI requires the latest backend, otherwise, the endpoints that support multi-routes aren't available (`v2/`)

* Scenario # 3: `kaoto-ui@main-branch` + `kaoto-backend@1.0.0` + `@kie-tools/*@0.29.0`
   * `vscode-kaoto` can now link `kaoto-ui`
   * `vscode-kaoto` doesn't compile because there's a breaking change between `@kie-tools/*@0.27.0` and `@kie-tools/*@0.29.0`
   * the latest UI requires the latest backend, otherwise, the endpoints that support multi-routes aren't available (`v2/`)

With all that said, what would be the best approach in your opinion to move forward with `kaoto-ui@main-branch` tests?

**Comment by lordrip** [comment]
@apupier Now that I think of it, it seems to me that usually our problems come from the dependencies mismatch, and probably a big part of that it's because of how we're interacting with `@kie-tools`.

I haven't tested it yet, but I believe that we could move everything regarding `@kie-tools` into `vscode-kaoto` and offer hooks to provide what would be missing from the interconnection point of view.

The way how I imagine this happening is moving everything inside the [kogito-integration](https://github.com/KaotoIO/kaoto-ui/tree/a71892ca6e7455e7f871797e4be8f1daf9be0055/src/kogito-integration) folder, into `vscode-kaoto`, this way the `@kie-tools` dependencies will be defined by `vscode-kaoto` hence the breaking changes will be handled in a single place.

**Comment by apupier** [comment]
> we could move everything regarding @kie-tools into vscode-kaoto

This will forbid to reuse in other environments, which is the point to use kie and their architecture

**Comment by apupier** [comment]
I think the best approach is to provide more frequent release of backend and UI to allow integrating small step by small step.
